name: publish-release

on:
  push:
    branches:
      - main

jobs:
  publish-release:
    if: github.repository == 'mdn/bob'
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: GoogleCloudPlatform/release-please-action@v4
        id: release

      - name: Setup
        if: steps.release.outputs.release_created
        uses: actions/checkout@v4

      - name: Checkout
        if: steps.release.outputs.release_created
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install
        if: steps.release.outputs.release_created
        run: npm ci

      - name: Publish
        if: steps.release.outputs.release_created
        run: npm publish
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_AUTH_TOKEN}}"
